version: '3.8'

services:
  api:
    build:
      context: infrastructure/api
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    networks:
      - backend

  prometheus:
    build:
      context: infrastructure/prometheus
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - api
    networks:
      - backend

  grafana:
    image: grafana/grafana:8.3.3
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - '3011:3000'
    depends_on:
      - prometheus
      - loki
    networks:
      - backend

  loki:
    image: grafana/loki:2.4.1
    volumes:
      - loki_data:/loki
    ports:
      - '3100:3100'
    networks:
      - backend

  promtail:
    build:
      context: infrastructure/promtail
      dockerfile: Dockerfile
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - backend

volumes:
  grafana_data:
  loki_data:

networks:
  backend:
