global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-application"
    static_configs:
      - targets: ["host.docker.internal:3030"]
